apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered-app
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
      - name: nodered
        image: yenaing/ubuntu_nodered
        ports:
        - containerPort: 1880
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostvol
          mountPath: /data
      volumes:
        - name: hostvol
          persistentVolumeClaim:
            # PVC name you created
            claimName: nodered-pvc
